spring:
  application:
    name: task-service
  datasource:
    url: ${FAMILYHUB_TASK_DATASOURCE_URL:jdbc:postgresql://localhost:5434/taskhub}
    username: ${FAMILYHUB_POSTGRES_USER}
    password: ${FAMILYHUB_POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${FAMILYHUB_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: record
server:
  address: 0.0.0.0
  port: 8081

family-hub:
  outbox:
    topic: familyhub.domain-events
    publish-delay-ms: 5000
  kafka:
    consumer:
      task-projections:
        group-id: task-service-task-projections
  security:
    internal:
      header-name: X-FamilyHub-Internal-Token
      token: ${FAMILYHUB_INTERNAL_TOKEN}
    jwt:
      secret: ${FAMILYHUB_JWT_SECRET}
  task:
    address-service-base-url: ${FAMILYHUB_ADDRESS_SERVICE_BASE_URL:http://localhost:8083}
    family-service-base-url: ${FAMILYHUB_FAMILY_SERVICE_BASE_URL:http://localhost:8084}
